### ISSUE TITLE
Remove Collectd references/dependency

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-os#3]
This agent relies on Collectd collecting metrics, which no longer makes sense.

**Comment by megastef** [comment]
The agent does not use collectd. It collects stats from /proc on Linux. But it ships logs in collectd format on non- linux platforms. The linux agent was changed to use the new metrics format. Changing the metrics format for other platforms needs to be done to drop collectd format in the spm receiver.

**Comment by otisg** [comment]
Ah, right, will open a separate issue for that.
