### ISSUE TITLE
Add ability to alias/obfuscate a hostname

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-os#5]
This would let one use a human-friendly name or obfuscate a sensitive hostname.
c.f. https://sematext.atlassian.net/wiki/display/PUBSPM/SPM+FAQ#SPMFAQ-CanhostnamesinSPMUIbeobfuscatedorcustomized

**Comment by megastef** [comment]
User could set a custom hostname by setting the environment variable SPM_REPORTED_HOSTNAME. This is already a feature of [spm-agent](https://github.com/sematext/spm-agent) module and works for all node based SPM agents (mongodb, apache, docker...).  
Do we need something else? E.g. sha256 hash of the real hostname?

**Comment by otisg** [comment]
Bingo, that is it!
